import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"

//const inter = Inter({ subsets: ["latin"] });

const outfit = localFont({
  src: "../../public/fonts/outfit/Outfit-VariableFont_wght.ttf",
  variable: '--font-outfit',
})

const youngSerif = localFont({
  src: "../../public/fonts/young-serif/YoungSerif-Regular.ttf",
  variable: '--font-youngSerif',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <title>Simple Omelette Recipe</title>
      <body className={`${youngSerif.variable} ${outfit.variable}`}>{children}</body>
    </html>
  );
}
